import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:intl/intl.dart';

class PdfService {
  /// Generates and shares/prints a high-tech PDF report
  static Future<void> exportReport({
    required int totalMinutes,
    required int currentXp,
    required int level,
    required Map<String, double> attributes,
  }) async {
    final pdf = pw.Document();
    final today = DateFormat('yyyy-MM-dd').format(DateTime.now());

    // Define Custom Colors (Monochrome Tech Theme)
    final PdfColor accent = PdfColor.fromInt(0xFF6C63FF);
    final PdfColor text = PdfColor.fromInt(0xFF2A2D3E);
    final PdfColor grey = PdfColor.fromInt(0xFF9E9E9E);
    final PdfColor lightGrey = PdfColor.fromInt(0xFFF5F5F5);

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pw.Container(
            padding: const pw.EdgeInsets.all(30),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                // --- HEADER ---
                pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Text("COMMAND CENTER REPORT", style: pw.TextStyle(fontSize: 20, fontWeight: pw.FontWeight.bold, color: text)),
                    pw.Text("DATE: $today", style: pw.TextStyle(fontSize: 10, color: grey)),
                  ],
                ),
                pw.Divider(color: accent, thickness: 2),
                pw.SizedBox(height: 20),

                // --- SUMMARY SECTION ---
                pw.Text("OPERATIVE STATUS", style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold, color: grey)),
                pw.SizedBox(height: 10),
                pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    _buildStatBox("FOCUS TIME", "${(totalMinutes / 60).toStringAsFixed(1)}h"),
                    _buildStatBox("CURRENT XP", "$currentXp"),
                    _buildStatBox("LEVEL", "LVL $level"),
                  ],
                ),
                pw.SizedBox(height: 30),

                // --- ATTRIBUTES TABLE ---
                pw.Text("ATTRIBUTE MATRIX", style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold, color: grey)),
                pw.SizedBox(height: 10),
                pw.Table(
                  border: pw.TableBorder.all(color: grey, width: 0.5),
                  children: [
                    // Table Header
                    pw.TableRow(
                      decoration: pw.BoxDecoration(color: lightGrey),
                      children: [
                        _buildCell("ATTRIBUTE", isHeader: true),
                        _buildCell("RATING (0-100)", isHeader: true),
                      ],
                    ),
                    // Table Data (Dynamic from Attributes Map)
                    ...attributes.entries.map((e) {
                      return pw.TableRow(
                        children: [
                          _buildCell(e.key),
                          _buildCell(e.value.toInt().toString()),
                        ],
                      );
                    }).toList(),
                  ],
                ),

                pw.Spacer(),

                // --- FOOTER ---
                pw.Divider(color: grey),
                pw.Center(
                  child: pw.Text("GENERATED BY STRIDE SYSTEM // ASTRA AI", style: pw.TextStyle(fontSize: 8, color: grey)),
                ),
              ],
            ),
          );
        },
      ),
    );

    // This triggers the native Share/Print dialog on the phone
    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => pdf.save(),
    );
  }

  // Helper for the stat boxes
  static pw.Widget _buildStatBox(String label, String value) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(15),
      width: 150,
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.grey300),
        borderRadius: pw.BorderRadius.circular(8),
      ),
      child: pw.Column(
        children: [
          pw.Text(label, style: pw.TextStyle(fontSize: 10, color: PdfColors.grey)),
          pw.SizedBox(height: 5),
          pw.Text(value, style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold)),
        ],
      ),
    );
  }

  // Helper for table cells
  static pw.Widget _buildCell(String text, {bool isHeader = false}) {
    return pw.Padding(
      padding: const pw.EdgeInsets.all(8),
      child: pw.Text(
        text,
        style: pw.TextStyle(
          fontWeight: isHeader ? pw.FontWeight.bold : pw.FontWeight.normal,
          fontSize: 10,
        ),
      ),
    );
  }
}