// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCncMtqy0EccqgW3csAHMUI0ciKSxAuuMg',
    appId: '1:509030814556:web:8ef3e3e213bf92fd4da799',
    messagingSenderId: '509030814556',
    projectId: 'stride-b1c44',
    authDomain: 'stride-b1c44.firebaseapp.com',
    storageBucket: 'stride-b1c44.firebasestorage.app',
    measurementId: 'G-RY76MF0HCZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLFE4KiRZ9ymrccGcPBq2CFziCRISZu58',
    appId: '1:509030814556:android:74e7e5b3c06274e54da799',
    messagingSenderId: '509030814556',
    projectId: 'stride-b1c44',
    storageBucket: 'stride-b1c44.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUE2hDnVgtM-N9mggeprvZOyEcnab7qkg',
    appId: '1:509030814556:ios:f62759d5e7ecae334da799',
    messagingSenderId: '509030814556',
    projectId: 'stride-b1c44',
    storageBucket: 'stride-b1c44.firebasestorage.app',
    androidClientId: '509030814556-hitjcqpa613o4v42u40s5ctuldvfa8i2.apps.googleusercontent.com',
    iosClientId: '509030814556-kmp8d17s4rlonioohrspatsf0tq9ftun.apps.googleusercontent.com',
    iosBundleId: 'com.example.stride',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUE2hDnVgtM-N9mggeprvZOyEcnab7qkg',
    appId: '1:509030814556:ios:f62759d5e7ecae334da799',
    messagingSenderId: '509030814556',
    projectId: 'stride-b1c44',
    storageBucket: 'stride-b1c44.firebasestorage.app',
    androidClientId: '509030814556-hitjcqpa613o4v42u40s5ctuldvfa8i2.apps.googleusercontent.com',
    iosClientId: '509030814556-kmp8d17s4rlonioohrspatsf0tq9ftun.apps.googleusercontent.com',
    iosBundleId: 'com.example.stride',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCncMtqy0EccqgW3csAHMUI0ciKSxAuuMg',
    appId: '1:509030814556:web:ba747719095879c44da799',
    messagingSenderId: '509030814556',
    projectId: 'stride-b1c44',
    authDomain: 'stride-b1c44.firebaseapp.com',
    storageBucket: 'stride-b1c44.firebasestorage.app',
    measurementId: 'G-37WESGRZ57',
  );
}
